# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljahw7bolKkhC0TQoPIRmuGXZONZ75q2
"""

#hello_python
print("Hello python")